# Generated by Django 4.2 on 2024-03-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_created_at_remove_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
    ]
